#!/bin/bash

set -e

TARGET_ARCH=x64

npm install

case $1 in
  build)
    node ./build/build.js
    npm run build-linux-$TARGET_ARCH
    ;;
  build-linux)
    node ./build/build.js
    npm run build-linux-arm
    npm run build-linux-arm64
    npm run build-linux-ia32
    npm run build-linux-x64
    ;;
  build-all)
    node ./build/build.js
    npm run build-linux-arm
    npm run build-linux-arm64
    npm run build-linux-ia32
    npm run build-linux-x64
    npm run build-win-arm64
    npm run build-win-ia32
    npm run build-win-x64
    npm run build-mac-arm64
    npm run build-mac-x64
    ;;
  dev)
    node ./build/build.js
    npm run dev
    ;;
  start)
    npm start
    ;;
  *)
    echo "$0 {build|build-linux|build-simulator|build-all|dev|start}"
    ;;
esac
