#!/bin/bash

set -e

# Mount essential filesystems
mount -t devtmpfs none /dev
mount -t proc proc /proc
mount -t sysfs sys /sys

# Create essential device nodes
mknod -m 600 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3

# Set environment variables
export OPENORCHID_WEBAPPS=/data/local/webapps
export OPENORCHID_WEBAPPS_JSON=/data/local/webapps.json
export OPENORCHID_DATA="$HOME/.profile"
export OPENORCHID_ADDONS="$OPENORCHID_DATA/extensions"
export OPENORCHID_STORAGE="$HOME"

export CURSOR_THEME=default

# Run linux system daemons
/sbin/wpa_supplicant -B -i wlan0 -c /system/etc/wpa_supplicant/wpa_supplicant.conf
/sbin/alsactl restore
/sbin/bluetoothd --daemon
/sbin/dhcpcd

# Launch and boot OrchidOS
/system/bin/aplay /system/etc/boot_sound.ogg
/system/bin/weston
  --idle-time=0 --shell=/system/bin/weston-desktop-shell
  --backend=wayland-backend.so --fullscreen /system/openorchid/openorchid \
  -- --type desktop

# Exit and shutdown gracefully
exit 0
shutdown -h now
