name: Build and Release OpenOrchid

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Linux (ARM 32-bit)
        run: npm run build-linux-arm
        if: matrix.platform == 'linux-arm'

      - name: Build Electron App for Linux (ARM 64-bit)
        run: npm run build-linux-arm64
        if: matrix.platform == 'linux-arm64'

      - name: Build Electron App for Linux (x64)
        run: npm run build-linux-x64
        if: matrix.platform == 'linux-x64'

      - name: Build Electron App for Windows (x64)
        run: npm run build-win-x64
        if: matrix.platform == 'win-x64'

      - name: Build Electron App for macOS (x64)
        run: npm run build-mac-x64
        if: matrix.platform == 'mac-x64'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0 # Change this to your desired tag
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/your-app-setup.exe # Replace with the actual path to your built Electron app installer
          asset_name: your-app-setup.exe
          asset_content_type: application/octet-stream

    strategy:
      matrix:
        platform: [linux-arm, linux-arm64, linux-x64, win-x64, mac-x64]
